name: todos_repository
description: A repository that handles todo related requests.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.10
  equatable: ^2.0.3
  firebase_core: ^1.13.1
  rxdart: ^0.27.3

dev_dependencies:
  mocktail: ^0.2.0
  test: ^1.17.0
  very_good_analysis: ^2.4.0
